### ISSUE TITLE
Cannot install inspec plugin for train-kubernetes

### ISSUE THREAD

**Issue by KonradSchieban** [bgeesaman/train-kubernetes#4]
When running `inspec plugin install train-kubernetes` I get the following error message:

```
Unrecognizable plugin structure - train-kubernetes - When installing from a path, please provide the path of the entry point file - installation failed.
```

Any idea how I can troubleshoot/fix this?
Using inspec version 4.18.104 on a Mac

**Comment by palladius** [comment]
I also can't install by following Docs and gem.

## Preconditions 

All met: 
* ruby 2.7.2p137
* inspec 4.23.15
* cat ~/.kube/config is used and florishing

## instllation 

1. gem install train-kubernetes

Successfully installed train-kubernetes-0.1.5
1 gem installed

2. inspec plugin install train-kubernetes
Unknown error occured - installation failed.

Let me know if I can trigger a more verbose output to help you troubleshoot.

**Comment by palladius** [comment]
Actually found the error:  can't activate faraday-1.1.0, already activated faraday-1.0.1 

riccardo@aspirina:~/git/inspec-gke-cis-benchmark$ 🐼 inspec plugin install train-kubernetes --log-level=debug | tee t
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-supermarket': an existing plugin with that name was loaded via bundle-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/bundles/inspec-supermarket.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-habitat': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-habitat/lib/inspec-habitat.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-compliance': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-compliance/lib/inspec-compliance.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-plugin-manager-cli': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-reporter-json-min': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-reporter-json-min/lib/inspec-reporter-json-min.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-reporter-junit': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-reporter-junit/lib/inspec-reporter-junit.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-reporter-html2': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-reporter-html2/lib/inspec-reporter-html2.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-init': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-init/lib/inspec-init.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'inspec-artifact': an existing plugin with that name was loaded via core-loading from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-artifact/lib/inspec-artifact.rb
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-habitat': an existing plugin with that name was loaded via system_gem-loading from train-habitat
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-aws': an existing plugin with that name was loaded via system_gem-loading from train-aws
[2020-11-02T11:55:50+01:00] DEBUG: PluginLoader: refusing to re-register plugin 'train-winrm': an existing plugin with that name was loaded via system_gem-loading from train-winrm
Traceback (most recent call last):
        22: from /home/riccardo/.rbenv/versions/2.7.2/bin/inspec:23:in `<main>'
        21: from /home/riccardo/.rbenv/versions/2.7.2/bin/inspec:23:in `load'
        20: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-bin-4.23.15/bin/inspec:11:in `<top (required)>'
        19: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/base_cli.rb:35:in `start'
        18: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        17: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        16: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        14: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        13: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        12: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        11: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        10: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         9: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:123:in `install'
         8: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:364:in `install_from_remote_gem'
         7: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:412:in `install_attempt_install'
         6: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:72:in `install'
         5: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:303:in `install_from_remote_gems'
         4: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:345:in `install_gem_to_plugins_dir'
         3: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:345:in `each'
         2: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:347:in `block in install_gem_to_plugins_dir'
         1: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/specification.rb:1365:in `activate'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/specification.rb:2237:in `check_version_conflict': can't activate faraday-1.1.0, already activated faraday-1.0.1 (Gem::LoadError)
        19: from /home/riccardo/.rbenv/versions/2.7.2/bin/inspec:23:in `<main>'
        18: from /home/riccardo/.rbenv/versions/2.7.2/bin/inspec:23:in `load'
        17: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-bin-4.23.15/bin/inspec:11:in `<top (required)>'
        16: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/base_cli.rb:35:in `start'
        15: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        14: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        13: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        12: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        11: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        10: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
         9: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
         8: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
         7: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
         6: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:123:in `install'
         5: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:364:in `install_from_remote_gem'
         4: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb:412:in `install_attempt_install'
         3: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:72:in `install'
         2: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:303:in `install_from_remote_gems'
         1: from /home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:344:in `install_gem_to_plugins_dir'
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:353:in `rescue in install_gem_to_plugins_dir': can't activate faraday-1.1.0, already activated faraday-1.0.1 (Inspec::Plugin::V2::InstallError)

**Comment by palladius** [comment]
🐼 gem list faraday

*** LOCAL GEMS ***

faraday (1.1.0, 1.0.1)
faraday-cookie_jar (0.0.7)
faraday_middleware (1.0.0)

🐼 gem uninstall faraday -v 1.0.1

You have requested to uninstall the gem:
        faraday-1.0.1

inspec-core-4.23.15 depends on faraday (>= 0.9.0, < 1.1)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  N

🐼 gem uninstall faraday -v 1.1.0
Successfully uninstalled faraday-1.1.0

## not it should work fine... lets see...

$ inspec plugin install train-kubernetes
Unknown error occured - installation failed.

$ inspec plugin install train-kubernetes --log-level=debug 
....
/home/riccardo/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/inspec-core-4.23.15/lib/inspec/plugin/v2/installer.rb:353:in `rescue in install_gem_to_plugins_dir': can't activate rubyzip-2.3.0, already activated rubyzip-1.3.0 (Inspec::Plugin::V2::InstallError)

**Comment by palladius** [comment]
riccardo@aspirina:~/git/inspec-gke-cis-benchmark$ 🐼 gem uninstall rubyzip -v 1.3.0

You have requested to uninstall the gem:
        rubyzip-1.3.0

inspec-core-4.23.15 depends on rubyzip (~> 1.2, >= 1.2.2)
winrm-fs-1.3.3 depends on rubyzip (~> 1.1)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  n
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)
riccardo@aspirina:~/git/inspec-gke-cis-benchmark$ 🐼 gem uninstall rubyzip -v 2.3.0

You have requested to uninstall the gem:
        rubyzip-2.3.0

winrm-fs-1.3.5 depends on rubyzip (~> 2.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  n
ERROR:  While executing gem ... (Gem::DependencyRemovalException)
    Uninstallation aborted due to dependent gem(s)

# Game over

**Comment by yulin99softrams** [comment]
cannot install train-kubernetes and got this error
$gem install train-kubernetes
ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
$gem --version
3.2.22
$ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

**Comment by rlakey** [comment]
Seeing the same error. Seems some of the dependencies at least don't like ruby 3?

ERROR:  While executing gem ... (NoMethodError)
    undefined method `request' for nil:NilClass
