### ISSUE TITLE
Invalid gemspec in dependent gems when installing train-kubernetes plugin

### ISSUE THREAD

**Issue by KonradSchieban** [bgeesaman/train-kubernetes#8]
I am seeing an issue when running inspec with the train-kubernetes plugin after installing the plugin using `inspec plugin install train-kubernetes`. The issue that I get is related to dependant gems yajl-ruby and recursive-open-struct. The stacktrace is here:

```
Invalid gemspec in [/home/konrad/.inspec/gems/2.7.0/gems/yajl-ruby-1.4.1/yajl-ruby.gemspec]: cannot load such file -- lib/yajl/version
Traceback (most recent call last):
        15: from /usr/bin/inspec:252:in `<main>'
        14: from /usr/bin/inspec:252:in `load'
        13: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.41.2/bin/inspec:10:in `<top (required)>'
        12: from /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        11: from /opt/inspec/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        10: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/cli.rb:465:in `<top (required)>'
         9: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/cli.rb:465:in `new'
         8: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/plugin/v2/loader.rb:39:in `initialize'
         7: from /opt/inspec/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `each'
         6: from /opt/inspec/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `each'
         5: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/plugin/v2/loader.rb:40:in `block in initialize'
         4: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/plugin/v2/loader.rb:290:in `fixup_train_plugin_status'
         3: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/plugin/v2/loader.rb:181:in `activate_managed_gems_for_plugin'
         2: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/plugin/v2/loader.rb:181:in `each'         1: from /opt/inspec/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.41.2/lib/inspec/plugin/v2/loader.rb:181:in `block in activate_managed_gems_for_plugin'/opt/inspec/embedded/lib/ruby/2.7.0/rubygems/resolver/vendor_set.rb:40:in `add_vendor_gem': unable to find /home/konrad/.inspec/gems/2.7.0/gems/yajl-ruby-1.4.1/yajl-ruby.gemspec for gem yajl-ruby (Gem::GemNotFoundException)
```

I can fix the issue by manually updating the gemspec file /home/konrad/.inspec/gems/2.7.0/gems/yajl-ruby-1.4.1/yajl-ruby.gemspec : I would replace the line with require from
```require './lib/yajl/version'```
to
```
lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'yajl/version'
```
manually updating the gemspecs cannot really be the final solution. The issue is somehow related to the path where the dependant gems are installed. I noticed that I have gems both in ~/.inspec/... and ~/.gems/... How can this be influenced?

**Comment by aaronlippold** [comment]
Is this issue resolved and can it be closed now?
